//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Data.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDetailsActivityLog
    {
        public long DriverDetailsActivityLogID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public int LicenceTypeID { get; set; }
        public string LicenceNo { get; set; }
        public string Pincode { get; set; }
        public bool Uber { get; set; }
        public bool Ola { get; set; }
        public bool IsReferred { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public long LastUpdatedBy { get; set; }
        public int DriverStatusID { get; set; }
        public string ExpectedSalary { get; set; }
        public int CityID { get; set; }
        public Nullable<System.DateTime> AttachedOn { get; set; }
        public Nullable<System.DateTime> PartnerMatchedOn { get; set; }
        public Nullable<System.DateTime> CompletedFirstTripOn { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        public virtual DriverStatus DriverStatu { get; set; }
        public virtual LicenceType LicenceType { get; set; }
    }
}
