//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Data.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenceType
    {
        public LicenceType()
        {
            this.DriverDetails = new HashSet<DriverDetail>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        public int LicenceTypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<DriverDetail> DriverDetails { get; set; }
    }
}
