//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Data.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerDetail
    {
        public OwnerDetail()
        {
            this.OwnerDetailsActivityLogs = new HashSet<OwnerDetailsActivityLog>();
        }
    
        public long OwnerDetailID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Pincode { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public long LastUpdatedBy { get; set; }
        public int CityID { get; set; }
        public Nullable<System.DateTime> FollowUpOn { get; set; }
        public string FollowUpNotes { get; set; }
        public Nullable<System.DateTime> NextFollowUp { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<OwnerDetailsActivityLog> OwnerDetailsActivityLogs { get; set; }
        public virtual User User { get; set; }
    }
}
