//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Data.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public string LoginProvider { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public string ProviderKey { get; set; }
        public long UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
